services:
  etcd:
    container_name: etcd
    image: bitnami/etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://localhost:2379
    ports:
      - '127.0.0.1:2379:2379' # client port
      - '127.0.0.1:2380:2380' # peer port
    volumes:
      - etcd-data:/etcd_data
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '127.0.0.1:4000:4000' # backend port
    depends_on:
      - etcd

volumes:
  etcd-data:
